### PR TITLE
WIP deployscript language

### PR DESCRIPTION
**Pull request by mhhf**
Work in Progress, please don't pull right now :)

### CODE REVIEW

**Comment by nmushegian** [comment]
Copy/pasting instructions from denis:

`./deployscript` in dapsys foulder:

```
var dsAuthFactory = new DSAuthFactory()
var dsDataFactory = new DSDataFactory()
var dsTokenFactory = new DSTokenFactory()
var dsMultisigFactory = new DSMultisigFactory()
var factory1 = new DSFactory1( dsDataFactory, dsTokenFactory, dsMultisigFactory, dsAuthFactory )

export factory1
```
run with: `dapple run deployscript -e morden`
will produce the output (fake addresses):
```
DEPLOYED: DSAuthFactory = 0x89e020ed6a30e8d5a05f6c6ee77a81c46934ba25
GAS COST: 510111 for "new DSAuthFactory"
Waiting for 4 confirmations: .... confirmed!
DEPLOYED: DSDataFactory = 0x17d41b0d0e290f9c6be4c610b7db654464ee6425
GAS COST: 1666288 for "new DSDataFactory"
Waiting for 4 confirmations: .... confirmed!
DEPLOYED: DSTokenFactory = 0xb079bbc9526a4668f3cd49a69a62fc1d3f17d24a
GAS COST: 2515751 for "new DSTokenFactory"
Waiting for 4 confirmations: .... confirmed!
DEPLOYED: DSMultisigFactory = 0x87af711cd9747bf265b2a84d38f6d5ba2b6eb065
GAS COST: 1644985 for "new DSMultisigFactory"
Waiting for 4 confirmations: .... confirmed!
DEPLOYED: DSFactory1 = 0x421e3aaaf1c41d7abae4842883b8307eddfd3fac
GAS COST: 832709 for "new DSFactory1"
Waiting for 4 confirmations: .... confirmed!
```
and leave the exports in `./dappfile`:
```
layout:
  sol_sources: contracts
  build_dir: build
ignore: []
environments:
  default:
    objects:
      factory1:
        class: DSFactory1
        address: ‚0x421e3aaaf1c41d7abae4842883b8307eddfd3fac'
```

**Comment by nmushegian** [comment]
* `-e morden` doesn't work yet.
* What is the "default" environment? Is it actually "morden" or some kind of "local"? I propose morden should be the default.

**Comment by nmushegian** [comment]
next highest priority is being able to import env variables into `maker-core`'s deploy scripts from `dappsys` (ie grab the factory and maybe ETH token).

Will notify when both codebases are unbroken =]

**Comment by mhhf** [comment]
> What is the "default" environment
default environment is whatever is specified as default in your .dapplerc
currently during the init, dapple defines its internal chain as the default environment as chain forking don't work atm

> -e morden doesn't work yet.
In order to make it work, you will have to specify a chain environment manually in your `.dapplerc` file.
My `.dapplerc` looks something like this:
```
environments:
  default:
    ethereum: internal
  evm: default
  morden:
    ethereum:
      host: 192.168.59.104
      port: '8545'
    ipfs:
      host: localhost
      port: '4001'
```

**Comment by nmushegian** [comment]
@ryepdx  might concern you as well,

Some terminology issues here. "ethereum" is the name of a blockchain and possibly environment, I think it confusing to use it as a key for specifying eth_rpc configuration. "evm" is a confusing name for an environment also.

Here's my proposed `.dapplerc`:

```
ipfs_config:
  host: ...
  port: ...
chain_env_connections:  # needs a good name
  ethereum:
      host: ...
      port: ...
  morden:
    ...
```

And the `environments` subtree of the dappfile:

```
environments:
  ethereum:
    objects:
      ...
  morden:
    objects:
      ...
```

**Comment by nmushegian** [comment]
What if each line in the script was automatically annotated with known state, like "// Pending: <trxid>" or "Done: <result>"? This could provide another layer of safety checks - you would need to manually delete a "Done" comment and re-run it, for example.

**Comment by mhhf** [comment]
I like the idea. 
But deploy scripts aren't associated to an environment the environment as well as the local scope of the deploy script would have to be stored as well.
```
1. // env: morden
2. var a = new A() // Done: a=0x53[...]2a
3. var b = new B( a ) // Pending: tx=0x12[...]ef
4. export b
```
If its more about the state tracking then about the readability I'd suggest a `deploy.<env>.log` file which contain this information.

**Comment by nmushegian** [comment]
Should be ok as long as the logs are stored alongside the template sequence and it's clear that dapple run is maintaining a stateful process per distinct run "start".

**Comment by ryepdx** [comment]
Just noticed the Travis CI PR checking appears to be turned off. `npm test` on `feature/deploydsl` doesn't get past the linter at present. @mhhf, I've made a copy of the branch and will be issuing a PR to your branch once I've got `npm test` working again. Please let me know ASAP if you've already addressed this or if you have commits you haven't pushed yet.

**Comment by ryepdx** [comment]
Thanks, @mhhf. :-)

**Comment by nmushegian** [comment]
https://github.com/mhhf/dapple/commit/a0823daf9f7a8eed704c6f57ab98c1f3f70156a8#diff-ae38a11a829764f7ca0d93c0e9318f7dR175  @mhhf

**Pull request merged**
