### PR TITLE
Add Dockerfile, `dapple-docker' script, update README

### PR DESCRIPTION
**Pull request by dbrock**
Perhaps this will be helpful to someone else who's not on one of the common Linux distributions.

We should use `nexusdev/dapple` instead of `dbrock/dapple` but I don't have access to the `nexusdev` Docker Hub account right now so I can't set up that automated build. (Are you the owner, @mhhf?)

### CODE REVIEW

**Comment by nmushegian** [comment]
Is `ddapple` a naming convention I'm not aware of? Otherwise, it's a confusing name.

**Comment by dbrock** [comment]
How about `dapple-docker`?

**Comment by dbrock** [comment]
And no, it's not a convention, it's just something I like to do because I tend to use this pattern a lot.

**Comment by nmushegian** [comment]
`dapple-docker` is much better

**Comment by dbrock** [comment]
Good call, I agree, `ddapple` may have been a bit confusing.

**Comment by dbrock** [comment]
I did the same for `geth` by the way: https://github.com/dbrock/dgeth

**Pull request merged**
