### PR TITLE
libraries support for dapple test

### PR DESCRIPTION
**Pull request by mhhf**
I get weird things with this approach. My guess is that EtherSim don't has full support for delegatecall or I fuck up the code during the substitution. Try the following example, which execute the test, but the test fails:
```
import 'dapple/test.sol';

library Math {
  function and(bool a, bool b) returns (bool c) {
    return a && b;
  }
}

contract A is Test {
  function testTrue() {
    assertEq( true, Math.and(true,true) );
  }
}
```
The following example crashes `  Error: VM Exception while executing transaction: invalid JUMP`:

```
import 'dapple/test.sol';

library Math {
  function and(bool a, bool b) returns (bool c) {
    return a && b;
  }
}

contract A is Test {
  function testTrue() {
    bool a=true;
    assertEq( true, Math.and(true,true) );
  }
}
```

### CODE REVIEW

**Comment by mhhf** [comment]
I made a minimal breaking example:
```
library Math {
  function and(bool a, bool b) returns (bool c) {
    return a && b;
  }
}

contract A{
  function testTrue() returns(bool){
    return Math.and(true, true);
  }
}
```

```
'use strict'

var Web3 = require('web3');
var classes = require('./classes.json');

// setup
var web3 = new Web3(new Web3.providers.HttpProvider("http://localhost:8545"));
web3.eth.defaultAccount = web3.eth.coinbase;
console.log('defaultAccount is', web3.eth.defaultAccount);

// deploy library
var Math = web3.eth.contract(JSON.parse(classes.Math.interface));
var mathLib = Math.new({
  data: classes.Math.bytecode,
  from: web3.eth.defaultAccount
});
var reciept = web3.eth.getTransactionReceipt(mathLib.transactionHash);
var libAddress = reciept.contractAddress;
console.log('library address is:',libAddress);


// substitude A binary code:
// bin also don't work if compiled with (math address should be substituded with one on chain)
// solc -o - --libraries "Math:4e6b4b45e5ed4ffa31acb881c3e6653ec7e80b0c" --combined-json bin libContract.sol| jq '.contracts.A.bin'|xargs echo $1 > A.bin
var bin = classes.A.bytecode.replace(/__([^_]+)_*/g, (matched, name) => {
  return libAddress.slice(2);
});

var A = web3.eth.contract(JSON.parse(classes.A.interface));
var aR = A.new({
  data: bin,
  from: web3.eth.defaultAccount
});
var reciept = web3.eth.getTransactionReceipt(aR.transactionHash);
var aaddress = reciept.contractAddress;
console.log('A address',aaddress);

// call
var a = A.at(aaddress);
var ret = a.testTrue.call();
console.log(ret);
```

**Comment by mhhf** [comment]
On morden with
Math: `0xcb264e62f89c121f785dc61daa97c1e3134a6653`
A: `0x1b7817b5f5184306d212be1c100b6dc49602bda4`

The execution fails:
`a.testTrue.call() === false`

**Comment by mhhf** [comment]
experimental support is working!

try this:
```
library A {
  function a(address contractAddress) returns (bool){
    return msg.sender == contractAddress;
  }
}
contract B is Test {
  function testDelegatecall() {
    assertFalse(A.a(address(this))); // user should be the sender
  }
}
```

**Comment by ryepdx** [comment]
Is this ready to be merged in?

**Comment by mhhf** [comment]
Almost. #230 still needs to be addressed, and also this observation: something in the dependency has changed (ethereum-lib/ vm/ block, etc.) and dapple test ist VERRY slow. Maybe its because of a system dependency of mine. Can you verify the speed on your machine e.g. on dappsys?

**Comment by ryepdx** [comment]
```
~/devenv/dappsys$ time dapple test
...
real	1m8.425s
user	1m3.149s
sys	0m3.039s
```

**Pull request merged**
