### PR TITLE
Dsl completion

### PR DESCRIPTION
**Pull request by ryepdx**

### CODE REVIEW

**Comment by ryepdx** [comment]
@mhhf, you might want to take a look at this to verify I'm not breaking anything non-obvious. Made some changes to the DSL's grammar.

**Comment by mhhf** [comment]
There was a problem with passing objects as deploy arguments: they got passed as objects and not as addresses. I made a PR in your branch which fixes this issue by holding internal representations always as typed expressions.

**Comment by mhhf** [comment]
oh, and silent logging don't seem to work, but hadn't looked at that one

**Comment by mhhf** [comment]
Otherwise its good :+1:, thanks for the fixes!
looking forward to use import statements :D

**Comment by ryepdx** [comment]
Thanks! Silent logging was working, but the streams being used in some of the DSL tests were not silencing their Interpreters. Updated the tests to silence those.

**Pull request merged**
