### PR TITLE
WIP `dapple publish` & `dapple install` from dapphubdb

### PR DESCRIPTION
**Pull request by mhhf**
First iteration that actually works.
Code is dirty and need to be refactored, which I will address next. 
Also error handling and proper logging needs to be implemented, but for testing purposes you can test it out of a dapple package with `dapple publish -e morden`

### CODE REVIEW

**Comment by mhhf** [comment]
@ryepdx: I refactored the ipfs stuff out of `dapple install`, you should peer review this.
Also `dapple install` from dapphubdb is now possible.
Currently I have a package header (json) in front of the the package root directory. 
This is a problem with your approach where the ipfs hash passed to `dapple install` is the hash to the root directory. Passing the ipfs hash of a package won't work.
A solution would be to check if the passed hash is a file or a directory, but do we want to have this?

**Comment by ryepdx** [comment]
Hey Denis, just so I'm clear on what you're saying: your preferred approach would be to have package IPFS hashes point to schema files which then contain the IPFS hash of the package's root directory. Is that correct?

My own inclination is to allow users to install packages outside of DappHub by passing in IPFS hashes, just as they can install packages via Git URLs. I don't think it would be huge deal to check if the root hash passed in points to a schema file or a directory, so I'm in favor of supporting both.

**Comment by mhhf** [comment]
The ipfs hash points to a json-object, the header file, which is specified by this schema: https://github.com/mhhf/dapple/blob/feature/publish/specs/package.json
In spore I used this for searching: In a decentral setting there isn't a central server where you can send your query to. A `dapple search` command will only be possible if is performed local. The header minimizes the size a user needs to download to be able to infer certain properties about a package.
( e.g. if the size of dapples package ecosystem will be 5% of npms, all headers would be ~50MB in size )
The header is also needed to include information, which is not directly stored in the dappfile: e.g. infos about the solidity version and compilation flags etc.
But I included it mostly because spore worked that way and dapphub is programmed do process and display the header file, this may be a wrong approach since a lot of information are available in the dappfile itself and therefore are ambiguous.

**Comment by mhhf** [comment]
Also: How should it handle dependencies: is everything included in the root ipfs-dir hash, or just certain explicitly selected files and the dependencies are installed recursively?

**Comment by nmushegian** [comment]
I favor specifying dependencies in the dappfile instead of including them in the package hash directly. Dependencies are either in dapphub or specified by hash some way and verifiable

**Comment by ryepdx** [comment]
Hey @mhhf, is this ready for merge now, or are there more changes you plan to make?

**Comment by mhhf** [comment]
Let me refactor the publish section tomorrow, I think it should be ready after that.

**Comment by nmushegian** [comment]
merging it in to get the grant features into the main branch

**Pull request merged**
