### PR TITLE
Crazy error message feature

### PR DESCRIPTION
**Pull request by dbrock**
It would be very useful if the error message that's displayed when an exception is thrown could somehow indicate where the error occured:

```
MakerTest
  test basic locking and freeing
  Error: VM Exception while executing transaction: invalid JUMP
```

I have managed to duct tape together a version of this functionality, such that the above error message now might look like this:

```
MakerTest
  test basic locking and freeing
  Error at `db.create_cdp_type(token, accumulator)'
```

Also, this source code

```
contract ExampleTest is Test {
    function test_silly() {
        var moomin = 123;
        var snufkin = 456;

        if (moomin != snufkin) {
            throw; // Failed to frobnicate the thingamajig
        }
    }
}
```

now produces the following error message:

```
ExampleTest
  test silly
  Error: Failed to frobnicate the thingamajig
```

This is all made possible by the following patch to `ethereumjs-vm`: https://github.com/dbrock/ethereumjs-vm/commit/b6149c932d1490b47490c54bea53553db6eff7ec

While undeniably useful, the current implementation of this is pretty much indescribably horrendous.

However, I just noticed after finishing this that there is a pull request on the Solidity compiler right now to add support for bytecode-level source mappings: https://github.com/ethereum/solidity/pull/699

Once that's merged into Solidity, this functionality can be implemented in a slightly more describably horrendous way.

It might also be possible to extend this to support full stack traces somehow.

cc @nmushegian @rainbeam @mhhf

### CODE REVIEW

**Comment by mhhf** [comment]
HAHAHA YESSSS <3

Love how deep you got into the dapple holes for this!!

This is part of this this FR, the other features should be done analog: https://github.com/nexusdev/dapple/issues/220

However, lets make this part of the v0.8 feature set, since its release is already in the pipeline and I took a similar route for some features. E.g. EtherSim dependency will get replaced by this: https://github.com/nexusdev/dapple-chain
with a custom ethereumjs-vm fork:
https://github.com/nexusdev/ethereumjs-vm/tree/web3env

I'll definitive have a closer look on this PR next week.

**Comment by nmushegian** [comment]
are you a wizard??

**Comment by rainbeam** [comment]
mate this is sick. +1000. This will save SO much time.

**Comment by kumavis** [comment]
Nicely done -- hope we can reconcile the nexus dev fork of ethereumjs-vm back into upstream/master

**Comment by kennyrowe** [comment]
Very nice @dbrock , also hope this can get get into the ethereumjs-vm

**Comment by dbrock** [comment]
Haha, thanks guys! :joy_cat: 

@mhhf Sounds good! Maybe we should create a milestone for 0.8?

@kumavis Yeah, definitely. Do you have any opinions about this change by any chance? https://github.com/dbrock/ethereumjs-vm/commit/b6149c932d1490b47490c54bea53553db6eff7ec

By the way if anyone wants to use this right now you should be able to just check out this branch and run `npm install`.

cc @jorisbontje

**Comment by dbrock** [comment]
Should I merge this? Branches really confuse me

**Comment by kumavis** [comment]
@dbrock thats very easily merge-able, my concern is that the `nexusdev/ethereumjs-vm` has grown very distant from `ethereumjs/ethereumjs-vm`

**Comment by dbrock** [comment]
@kumavis Hmm... I don't see that. Which branch are you talking about?

**Comment by kumavis** [comment]
@dbrock ah! My mistake. Looks good. https://github.com/ethereumjs/ethereumjs-vm/compare/master...dbrock:master

**Comment by dbrock** [comment]
> I just noticed after finishing this that there is a pull request on the Solidity compiler right now to add support for bytecode-level source mappings: ethereum/solidity#699
>
> Once that's merged into Solidity, this functionality can be implemented in a slightly more describably horrendous way.

This is now not just merged but released! :fireworks: :icecream: :lollipop: :beers: 

https://github.com/ethereum/solidity/releases/tag/v0.3.6

**Comment by dbrock** [comment]
Yay, https://github.com/ethereumjs/ethereumjs-vm/pull/80 also merged, thanks @kumavis!

This can now be rewritten to use the new bytecode source mapping, which should be more reliable.

**Pull request merged**
